import Head from 'next/head'

import Home from '@/src/components/screens/home/Home'
import { GetStaticProps } from 'next'



export default function HomePage() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Home />
		</>
	)
}

export const getStaticProps:GetStaticProps = async() => {
	return{
		props: {

		}
	}
}
